SELECT
CASE WHEN G.GRADE<8 THEN NULL
    ELSE S.NAME END AS NAME,
G.GRADE,
S.MARKS
FROM
STUDENTS S
JOIN 
GRADES G
ON S.MARKS>=G.MIN_MARK AND S.MARKS<=G.MAX_MARK
ORDER BY 
G.GRADE DESC, NAME ASC, S.MARKS